sync_config:
  big_file_threshold: null
  branch: master
  delete_target_directory: false
  depth: -1
  email: tommy@mage.ai
  pack_size_limit: null
  remote_repo_link: https://github.com/mage-ai/rag-test.git
  repo_path: /home/projects/test/pro
  sync_on_pipeline_run: true
  sync_on_start: null
  sync_submodules: true
  username: tommydangerous
